### PR TITLE
add more types

### PR DESCRIPTION
**Pull request by bconnorwhite**
Added a few more types

### CODE REVIEW

**Comment by ScanMountGoat** [comment]
Thanks for looking into this. For vertex formats, the vector sizes should match up with the format like `VectorSize::Quad` only having vertex formats ending in `...x4`. Not all widths are currently supported by WGPU. The convention for values like u8 is to pack them into larger sizes like u32. I'll create an issue for tracking what types need to be supported. We really only need to support the formats listed here: https://docs.rs/wgpu/0.13.1/wgpu/enum.VertexFormat.html

**Comment by ScanMountGoat** [comment]
I'm tracking the types that need to be added in #22. This PR doesn't need to cover all of them of course. Once the quad formats are fixed and the test is updated in lib.rs, this should be good to merge.

**Comment by bconnorwhite** [comment]
Fixed the x4 typo. I wasn't sure how you want to handle unorm/snorm types where a given wgsl type can map to multiple vertex formats

**Comment by ScanMountGoat** [comment]
> Fixed the x4 typo. I wasn't sure how you want to handle unorm/snorm types where a given wgsl type can map to multiple vertex formats
Are you referring to formats that get converted to float like `Unorm8x2` vs `Snorm8x2`? I'm not sure if there's a great way of handling this purely based on the data we get out of WGSL. I'll make a note of this in the limitations for now. 

The changes look good to merge.

**Pull request merged**
