### PR TITLE
Expose shader source

### PR DESCRIPTION
**Pull request by stefnotch**
I needed access to the shader source so that I could create the shader module with a custom label.

And I also wanted access to the source so that I can patch shader functions on the fly.

### CODE REVIEW

**Comment by ScanMountGoat** [comment]
> I needed access to the shader source so that I could create the shader module with a custom label.

I've found adding a label to just the pipeline to be sufficient for my debugging. If you think setting the module label would be helpful, you could add a separate function that takes a label to the generated code. It should also be possible to just write your own function and avoid using wgsl_to_wgpu for creating the module itself.

> And I also wanted access to the source so that I can patch shader functions on the fly.

If you're modifying the shader source at build time, you can just modify the source before passing it to wgsl_to_wgpu. If you need to modify the source at runtime, there's no longer any guarantee that the bindings generated by wgsl_to_wgpu are correct.

**Comment by stefnotch** [comment]
I'm using this for an app that's compiled to WASM, so there's always a bit of "keeping the binary size down". If I use `wgsl_to_wgpu`, but then need to separately inject the shaders into the binary, then I believe I'd end up with two copies of the shaders. 

> If you need to modify the source at runtime, there's no longer any guarantee that the bindings generated by wgsl_to_wgpu are correct

There are two cases where currently I do that. One is purely for debug purposes, so it's fine if the guarantees are broken. And the other one is constrained to be "replace a single function's body", which we need for swapping out the underlying "parametric function that maps a 2D value to a 3D coordinate". [Demo](https://math2model.cg.tuwien.ac.at/#/)

Another case is for swapping out `const` values in a WGSL shaders in places where pipeline-overridable constants cannot be used, due to WGSL restrictions. [Examples](https://github.com/wgsl-tooling-wg/wesl-spec/issues/54#issuecomment-2408901953)

I would be more than happy to expose the source as something that's clearly marked as "the user is responsible for the guarantees" or `unsafe`.

**Comment by ScanMountGoat** [comment]
That makes sense. Does it cover your use cases to just make the shader source public like in this PR?

**Comment by stefnotch** [comment]
Yes, that fully covers my use-cases.

**Pull request merged**
