### PR TITLE
Generate entry point constants and VertexState functions

### PR DESCRIPTION
**Pull request by AndrewBrownK**
I think this captures what was described in the discussion at https://github.com/ScanMountGoat/wgsl_to_wgpu/pull/30

> Code that generates the entire wgpu::VertexState for each vertex entry point in the shader module. This would probably need to be a function since the step modes need to be provided by the user.

### CODE REVIEW

**Comment by AndrewBrownK** [comment]
erk, actually this has problems still. 

We can't accept the `VertexStepModes` as arguments and invoke the `vertex_buffer_layout` functions on our own, due to the lifetime requirements of the array of `VertexBufferLayout` in `VertexState`. However if the user of the functions generating `VertexStates` has to provide their own array of `VertexBufferLayouts`, then we are not really saving them any complexity (e.g. ensuring the right layouts are paired with the right entry function name).

**Comment by ScanMountGoat** [comment]
> We can't accept the `VertexStepModes` as arguments and invoke the `vertex_buffer_layout` functions on our own, due to the lifetime requirements of the array of `VertexBufferLayout` in `VertexState`.

I'm getting an error about referencing a local variable that gets dropped when the function returns. This should be an easy fix though. Just create a temporary variable that owns the buffers and pass that as a reference to the function instead. The function for each entry point will return `VertexEntry` instead of the entire `VertexState`. The usage should look almost identical for the user. Feel free to adjust things slightly as needed.

```rust
struct VertexEntry<const N: usize> {
    entry_point: &'static str,
    buffers: [wgpu::VertexBufferLayout<'static>; N],
}

fn vertex_state<'a, const N: usize>(
    module: &'a wgpu::ShaderModule,
    entry: &'a VertexEntry<N>,
) -> wgpu::VertexState<'a> {
    wgpu::VertexState {
        module,
        entry_point: entry.entry_point,
        buffers: &entry.buffers,
    }
}
```

The user could call it like `vertex: vertex_state(&module, &vs_main_vertex_entry(step_mode_params))`

**Comment by ScanMountGoat** [comment]
@AndrewBrownK Just wanting to check if there was still interest in working on this or if you had any questions. I'll probably end up squashing and merging, so I wouldn't worry about creating a clean history when resolving the conflicts.

**Comment by AndrewBrownK** [comment]
@ScanMountGoat  sorry for the absence. Here are some thoughts for disucssion. We could do the `vertex_state` function and `VertexEntry` struct (with static lifetimes) like you describe, but it doesn't quite sit right for me.

- it doesn't really save the user any work or hide away complexity. Instead of just binding a `module`, `entry_point`, and `buffers` to a `VertexState` directly, you still have to specify all 3 of these parts but disjointed between the `vertex_state` invocation and `VertexEntry` construction. It's possible, but not very motivated.
- it forces the `VertexBufferLayouts` to be `'static`, when we only need to be `'a`. It's not that forcing `'static` is so bad, but it doesn't save any work for the user. The user will have to define static invocations of `vertex_buffer_layout(step_mode)`. But if the user has to define/invoke their own `vertex_buffer_layout` anyway, then why force it to be `'static`?

Some things I like:

- `entry_point: &'static str`, I think this will be especially good if we provide a const for each entry point name (I'll downsize this PR to just this feature, pending further discussion)
- Giving the `buffers` a statically fixed size, if that makes sense

**Comment by ScanMountGoat** [comment]
This is an example of the the code you have to type now.
```rust
vertex: wgpu::VertexState {
    module: &module,
    entry_point: "vs_main",
    buffers: &[
        shader::model::VertexInput::vertex_buffer_layout(wgpu::VertexStepMode::Vertex),
        shader::model::InstanceInput::vertex_buffer_layout(wgpu::VertexStepMode::Instance),
    ],
},
```
This would be after the suggested changes. The user no longer needs to specify the entry point string or the number and types of the vertex input structs.
```rust
vertex: shader::vertex_state(
    &module,
    &shader::vs_main_entry(wgpu::VertexStepMode::Vertex, wgpu::VertexStepMode::Instance),
),
```

wgsl_to_wgpu would just need to generate something like this for each vertex entry point.
```rust
fn vs_main_entry(
    vertex_input: wgpu::VertexStepMode,
    instance_input: wgpu::VertexStepMode,
) -> VertexEntry<2> {
    VertexEntry {
        entry_point: "vs_main",
        buffers: [
            shader::model::VertexInput::vertex_buffer_layout(vertex_input),
            shader::model::InstanceInput::vertex_buffer_layout(instance_input),
        ],
    }
}
```

**Comment by AndrewBrownK** [comment]
Okay I see now. I can implement this shortly

**Comment by AndrewBrownK** [comment]
I think we got it! Thanks for the sharp insights and detailed examples

**Pull request merged**
